In [1]:
import pandas as pd
import numpy as np

In [2]:
pd.__version__

'2.3.1'

In [3]:
df = pd.read_csv('https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv')

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                  170            3.0       159.0     3413.433759   
1                  130            5.0        97.0     3149.664934   
2                  170            NaN        78.0     3079.038997   
3                  220            4.0         NaN     2542.392402   
4                  210            1.0       140.0     3460.870990   

   acceleration  model_year  origin fuel_type         drivetrain  num_doors  \
0          17.7        2003  Europe  Gasoline    All-wheel drive        0.0   
1          17.8        2007     USA  Gasoline  Front-wheel drive        0.0   
2          15.1        2018  Europe  Gasoline  Front-wheel drive        0.0   
3          20.2        2009     USA    Diesel    All-wheel drive        2.0   
4          14.4        2009  Europe  Gasoline    All-wheel drive        2.0   

   fuel_efficiency_mpg  
0            13.231729  
1            13.688217  
2            14.246341  
3            16.912736  
4            12.488369

In [4]:
len(df)

9704

In [5]:
df['fuel_type'].nunique()

2

In [6]:
df[df['origin'] == 'Asia']['fuel_efficiency_mpg'].max()

np.float64(23.759122836520497)

In [7]:
df['horsepower'].median()

np.float64(149.0)

In [8]:
df['horsepower'].value_counts().max()

np.int64(142)

In [9]:
df[['horsepower']] = df[['horsepower']].fillna(value=142)

In [10]:
df['horsepower'].median()

np.float64(146.0)

In [11]:
asians = df[df.origin.eq('Asia')]
print(asians)

      engine_displacement  num_cylinders  horsepower  vehicle_weight  \
8                     250            1.0       174.0     2714.219310   
12                    320            5.0       145.0     2783.868974   
14                    200            6.0       160.0     3582.687368   
20                    150            3.0       197.0     2231.808142   
21                    160            4.0       133.0     2659.431451   
...                   ...            ...         ...             ...   
9688                  260            4.0       142.0     3948.404625   
9692                  180            3.0       188.0     3680.341381   
9693                  280            2.0       148.0     2545.070139   
9698                  180            1.0       131.0     3107.427820   
9703                  270            3.0       140.0     2908.043477   

      acceleration  model_year origin fuel_type         drivetrain  num_doors  \
8             10.3        2016   Asia    Diesel  Front

In [12]:
asiancolumns = asians.loc[:,['vehicle_weight','model_year']].head(7)
print(asiancolumns)

    vehicle_weight  model_year
8      2714.219310        2016
12     2783.868974        2010
14     3582.687368        2007
20     2231.808142        2011
21     2659.431451        2016
34     2844.227534        2014
38     3761.994038        2019


In [13]:
x = asiancolumns.to_numpy()
print(x)

[[2714.21930965 2016.        ]
 [2783.86897424 2010.        ]
 [3582.68736772 2007.        ]
 [2231.8081416  2011.        ]
 [2659.43145076 2016.        ]
 [2844.22753389 2014.        ]
 [3761.99403819 2019.        ]]


In [14]:
xtransp = x.transpose()
print(xtransp)

[[2714.21930965 2783.86897424 3582.68736772 2231.8081416  2659.43145076
  2844.22753389 3761.99403819]
 [2016.         2010.         2007.         2011.         2016.
  2014.         2019.        ]]


In [15]:
xtx = xtransp @ x
print(xtx)

[[62248334.33150762 41431216.5073268 ]
 [41431216.5073268  28373339.        ]]


In [16]:
invertxtx = np.linalg.pinv(xtx)
print(invertxtx)

[[ 5.71497081e-07 -8.34509443e-07]
 [-8.34509443e-07  1.25380877e-06]]


In [17]:
y = [1100, 1300, 800, 900, 1000, 1100, 1200]

In [18]:
invxtxtranx = invertxtx @ xtx
print(invxtxtranx)

[[ 1.00000000e+00 -2.32993395e-15]
 [-2.03925858e-15  1.00000000e+00]]


In [19]:
w = np.outer(y, invxtxtranx)
print(w)

[[ 1.10000000e+03 -2.56292735e-12 -2.24318444e-12  1.10000000e+03]
 [ 1.30000000e+03 -3.02891414e-12 -2.65103616e-12  1.30000000e+03]
 [ 8.00000000e+02 -1.86394716e-12 -1.63140686e-12  8.00000000e+02]
 [ 9.00000000e+02 -2.09694056e-12 -1.83533272e-12  9.00000000e+02]
 [ 1.00000000e+03 -2.32993395e-12 -2.03925858e-12  1.00000000e+03]
 [ 1.10000000e+03 -2.56292735e-12 -2.24318444e-12  1.10000000e+03]
 [ 1.20000000e+03 -2.79592074e-12 -2.44711030e-12  1.20000000e+03]]


In [20]:
elementsum = sum(w)
print(elementsum)

[ 7.40000000e+03 -1.72415112e-11 -1.50905135e-11  7.40000000e+03]
